[CUDA_Runtime_jll]
local = "true"
version = "12.8"

[HDF5]
libhdf5 = "/user-environment/linux-sles15-neoverse_v2/gcc-13.3.0/hdf5-1.14.5-ggey6bse2zevr4qvrgeen6thszi7hqrs/lib/libhdf5.so"
libhdf5_hl = "/user-environment/linux-sles15-neoverse_v2/gcc-13.3.0/hdf5-1.14.5-ggey6bse2zevr4qvrgeen6thszi7hqrs/lib/libhdf5_hl.so"

[HDF5_jll]
libhdf5_hl_path = "/user-environment/linux-sles15-neoverse_v2/gcc-13.3.0/hdf5-1.14.5-ggey6bse2zevr4qvrgeen6thszi7hqrs/lib/libhdf5_hl.so"
libhdf5_path = "/user-environment/linux-sles15-neoverse_v2/gcc-13.3.0/hdf5-1.14.5-ggey6bse2zevr4qvrgeen6thszi7hqrs/lib/libhdf5.so"

[MPIPreferences]
__clear__ = ["preloads_env_switch"]
_format = "1.0"
abi = "MPICH"
binary = "system"
cclibs = []
libmpi = "/user-environment/linux-sles15-neoverse_v2/gcc-13.3.0/cray-mpich-8.1.30-s55n4kydmg4edn2tcjb75ep3q7yngsx4/lib/libmpi"
mpiexec = ["srun"]
preloads = []
